version: '3.8'

networks:
  default:
    external: true
    name: mainNetwork

services:
  nginx:
    image: nginx:latest
    container_name: 'Recruitment-NGINX'
    ports:
      - '8202:80'
    volumes:
      - .:/var/www/recruitment
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: Recruitment-php
    volumes:
      - .:/var/www/recruitment
      - ./docker/php/www.conf:/usr/local/etc/php/conf.d/www.conf
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: unless-stopped